name: EditorConfig

on:
    pull_request:
    push:
        branches: master
    workflow_dispatch:

jobs:
    lint:
        runs-on: [ubuntu-latest, windows-latest]
        strategy:
            matrix:
                node-version: [14, 16]
        steps:
            - name: Get repository code
            uses: actions/checkout@v2
            - name: Check in node matrix
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
            run: npm ci
            - name: Run script
            run: npm run lint:editorconfig
