name: EditorConfig

on:
    pull_request:
    push:
        branches: master
    workflow_dispatch:

jobs:
    lint:
        runs-on: [ubuntu-latest, windows-latest]
        strategy:
            matrix:
                node-version: [14, 16]
        steps:
            - name: Get the source code
            uses: actions/checkout@v2
            - name: Test on type of node
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
            run: npm ci
            - name: Run test
            run: npm run lint:editorconfig
